all_managers_dic = {
                    263589: 'Germany 🇩🇪',
                    236729: 'United States 🇺🇲',
                    243671: 'South Korea 🇰🇷',
                    236062: 'Great Britain 🇬🇧',
                    236257: 'France 🇫🇷',
                    236216: 'The Soviet Union ☭',
                    243654: 'Australia 🇦🇺',
                    253790: 'Hungary 🇭🇺',
                    236145: 'New Zealand 🇳🇿',
                    236453: 'Italy 🇮🇹',
                    236143: 'Argentina 🇦🇷',
                    263294: 'Netherlands 🇳🇱',
                    236479: 'Japan 🇯🇵',
                    237205: 'China 🇨🇳',
                    236057: 'Canada 🇨🇦',
                    235910: '🏁Referee 6🏁'
                    }


collective_medas_up_to_gw_8 ={'Germany 🇩🇪': [11, 8, 7, 5, 2], 'United States 🇺🇲': [7, 7, 6, 6, 8], 'South Korea 🇰🇷': [9, 3, 9, 12, 4], 'Great Britain 🇬🇧': [4, 11, 5, 6, 10], 'France 🇫🇷': [4, 9, 5, 2, 5], 'The Soviet Union ☭': [5, 6, 5, 4, 5], 'Australia 🇦🇺': [6, 7, 5, 5, 4], 'Hungary 🇭🇺': [10, 9, 6, 8, 4], 'New Zealand 🇳🇿': [0, 2, 5, 10, 7], 'Italy 🇮🇹': [6, 9, 4, 7, 6], 'Argentina 🇦🇷': [3, 3, 8, 2, 4], 'Netherlands 🇳🇱': [5, 3, 4, 7, 6], 'Japan 🇯🇵': [4, 2, 3, 4, 8], 'China 🇨🇳': [3, 3, 4, 1, 6], 'Canada 🇨🇦': [7, 2, 8, 5, 5]}


German_leagues_ids = [56490, 56760, 57026, 58512, 58924, 59081, 59176, 59219, 60061, 60068, 60279, 60283]
# German_leagues_ids = [58512, 58924, 59081,]

German_leagues_ids_dic = {
    56490: "SEOUL",
    56760: "LONDON",
    57026: "ATHENS",
    58512: "BEIJING",
    58924: "SYDNEY",
    59081: "BERLIN",
    59176: "TOKYO",
    59219: "PARIS",
    60061: "ROME",
    60068: "HELSINKI",
    60279: "RIO",
    60283: "MEXICO CITY",
}

league_city_plus_managers = {'SEOUL': {224460: 'China 🇨🇳',
  225599: 'France 🇫🇷',
  225789: 'New Zealand 🇳🇿',
  226467: 'Great Britain 🇬🇧',
  224334: 'Japan 🇯🇵',
  227775: 'Canada 🇨🇦',
  230335: 'Netherlands 🇳🇱',
  225086: 'South Korea 🇰🇷',
  250605: 'Australia 🇦🇺',
  224564: 'Italy 🇮🇹',
  225574: 'Germany 🇩🇪',
  225799: 'Hungary 🇭🇺',
  224735: 'The Soviet Union ☭',
  224644: 'Argentina 🇦🇷',
  225155: 'United States 🇺🇲'},
 'LONDON': {225469: 'South Korea 🇰🇷',
  229078: 'Hungary 🇭🇺',
  226113: 'Germany 🇩🇪',
  225820: 'Great Britain 🇬🇧',
  225733: 'New Zealand 🇳🇿',
  226648: 'Canada 🇨🇦',
  226897: 'The Soviet Union ☭',
  263769: 'Australia 🇦🇺',
  227581: 'Japan 🇯🇵',
  227478: 'China 🇨🇳',
  230713: 'United States 🇺🇲',
  227289: 'France 🇫🇷',
  225537: 'Netherlands 🇳🇱',
  249169: 'Italy 🇮🇹',
  245690: 'Argentina 🇦🇷'},
 'ATHENS': {243586: 'Canada 🇨🇦',
  226944: 'Great Britain 🇬🇧',
  228841: 'United States 🇺🇲',
  228449: 'Italy 🇮🇹',
  226718: 'Hungary 🇭🇺',
  233668: 'Australia 🇦🇺',
  226891: 'Japan 🇯🇵',
  226934: 'New Zealand 🇳🇿',
  227213: 'Germany 🇩🇪',
  266196: 'France 🇫🇷',
  241504: 'South Korea 🇰🇷',
  227576: 'The Soviet Union ☭',
  227061: 'China 🇨🇳'},
 'BEIJING': {233264: 'Great Britain 🇬🇧',
  241636: 'Germany 🇩🇪',
  237763: 'United States 🇺🇲',
  233312: 'The Soviet Union ☭',
  233281: 'China 🇨🇳',
  244076: 'Netherlands 🇳🇱',
  264810: 'France 🇫🇷',
  233381: 'Canada 🇨🇦',
  236246: 'Hungary 🇭🇺',
  233427: 'Japan 🇯🇵',
  262557: 'Italy 🇮🇹',
  246849: 'New Zealand 🇳🇿',
  233912: 'Australia 🇦🇺',
  245687: 'Argentina 🇦🇷',
  237631: 'South Korea 🇰🇷'},
 'SYDNEY': {235303: 'South Korea 🇰🇷',
  252039: 'Germany 🇩🇪',
  235546: 'The Soviet Union ☭',
  242529: 'Italy 🇮🇹',
  260309: 'Australia 🇦🇺',
  263615: 'Japan 🇯🇵',
  235707: 'Netherlands 🇳🇱',
  263846: 'Argentina 🇦🇷',
  248288: 'United States 🇺🇲',
  240108: 'France 🇫🇷',
  236659: 'Great Britain 🇬🇧',
  257049: 'Canada 🇨🇦',
  236079: 'Hungary 🇭🇺'},
 'BERLIN': {236145: 'New Zealand 🇳🇿',
  243671: 'South Korea 🇰🇷',
  237205: 'China 🇨🇳',
  236062: 'Great Britain 🇬🇧',
  263589: 'Germany 🇩🇪',
  236479: 'Japan 🇯🇵',
  263294: 'Netherlands 🇳🇱',
  236729: 'United States 🇺🇲',
  236453: 'Italy 🇮🇹',
  243654: 'Australia 🇦🇺',
  236216: 'The Soviet Union ☭',
  236143: 'Argentina 🇦🇷',
  236257: 'France 🇫🇷',
  236057: 'Canada 🇨🇦',
  253790: 'Hungary 🇭🇺'},
 'TOKYO': {236638: 'The Soviet Union ☭',
  237153: 'Italy 🇮🇹',
  236666: 'South Korea 🇰🇷',
  263035: 'Great Britain 🇬🇧',
  236325: 'Canada 🇨🇦',
  236699: 'France 🇫🇷',
  236498: 'Germany 🇩🇪',
  236541: 'Japan 🇯🇵',
  241703: 'United States 🇺🇲',
  267348: 'New Zealand 🇳🇿',
  236606: 'China 🇨🇳',
  237877: 'Netherlands 🇳🇱',
  243192: 'Argentina 🇦🇷',
  236701: 'Hungary 🇭🇺',
  236521: 'Australia 🇦🇺'},
 'PARIS': {237840: 'France 🇫🇷',
  250070: 'Australia 🇦🇺',
  241777: 'United States 🇺🇲',
  241608: 'Hungary 🇭🇺',
  238137: 'Italy 🇮🇹',
  236658: 'New Zealand 🇳🇿',
  236890: 'Netherlands 🇳🇱',
  240576: 'Canada 🇨🇦',
  246294: 'Great Britain 🇬🇧',
  260554: 'South Korea 🇰🇷',
  249472: 'The Soviet Union ☭',
  244847: 'China 🇨🇳',
  245692: 'Germany 🇩🇪'},
 'ROME': {241693: 'New Zealand 🇳🇿',
  242692: 'United States 🇺🇲',
  241583: 'France 🇫🇷',
  241539: 'China 🇨🇳',
  243069: 'Canada 🇨🇦',
  243140: 'South Korea 🇰🇷',
  241590: 'Australia 🇦🇺',
  241390: 'Japan 🇯🇵',
  247863: 'Hungary 🇭🇺',
  243897: 'Netherlands 🇳🇱',
  241343: 'Italy 🇮🇹',
  244946: 'Germany 🇩🇪',
  243390: 'Great Britain 🇬🇧',
  243452: 'The Soviet Union ☭'},
 'HELSINKI': {246848: 'Hungary 🇭🇺',
  241096: 'South Korea 🇰🇷',
  242329: 'Italy 🇮🇹',
  241292: 'Canada 🇨🇦',
  253063: 'The Soviet Union ☭',
  243642: 'France 🇫🇷',
  245251: 'Great Britain 🇬🇧',
  241449: 'Netherlands 🇳🇱',
  262345: 'Australia 🇦🇺',
  267356: 'Japan 🇯🇵',
  250407: 'China 🇨🇳',
  242175: 'Germany 🇩🇪',
  247828: 'United States 🇺🇲'},
 'RIO': {262638: 'South Korea 🇰🇷',
  244838: 'Germany 🇩🇪',
  246158: 'Hungary 🇭🇺',
  252486: 'The Soviet Union ☭',
  244742: 'Netherlands 🇳🇱',
  251317: 'France 🇫🇷',
  262556: 'Great Britain 🇬🇧',
  262791: 'Italy 🇮🇹',
  241626: 'Canada 🇨🇦',
  245094: 'China 🇨🇳',
  251432: 'Australia 🇦🇺',
  245111: 'United States 🇺🇲',
  244914: 'Japan 🇯🇵',
  244707: 'New Zealand 🇳🇿'},
 'MEXICO CITY': {254909: 'The Soviet Union ☭',
  247864: 'Argentina 🇦🇷',
  244827: 'New Zealand 🇳🇿',
  262805: 'Netherlands 🇳🇱',
  241840: 'Canada 🇨🇦',
  245156: 'China 🇨🇳',
  245005: 'South Korea 🇰🇷',
  245061: 'United States 🇺🇲',
  248195: 'France 🇫🇷',
  244966: 'Italy 🇮🇹',
  247921: 'Australia 🇦🇺',
  245972: 'Japan 🇯🇵',
  246940: 'Hungary 🇭🇺',
  244944: 'Germany 🇩🇪',
  246496: 'Great Britain 🇬🇧'}}

My_german_managers = {225574: 56490,
 226113: 56760,
 227213: 57026,
 241636: 58512,
 252039: 58924,
 263589: 59081,
 236498: 59176,
 245692: 59219,
 244946: 60061,
 242175: 60068,
 244838: 60279,
 244944: 60283}

good_flags = {"ğŸ‡©ğŸ‡ª": 'Germany 🇩🇪',
                    "ğŸ‡ºğŸ‡¸": 'United States 🇺🇲',
                    "ğŸ‡°ğŸ‡·": 'South Korea 🇰🇷',
                    "ğŸ‡¬ğŸ‡§": 'Great Britain 🇬🇧',
                    "ğŸ‡¨ğŸ‡µ": 'France 🇫🇷',
                    "ovi": 'The Soviet Union ☭',
                    "ğŸ‡¦ğŸ‡º": 'Australia 🇦🇺',
                    "ğŸ‡­ğŸ‡º": 'Hungary 🇭🇺',
                    "ğŸ‡³ğŸ‡¿": 'New Zealand 🇳🇿',
                    "ğŸ‡®ğŸ‡¹": 'Italy 🇮🇹',
                    "ğŸ‡¦ğŸ‡·": 'Argentina 🇦🇷',
                    "ğŸ‡³ğŸ‡±": 'Netherlands 🇳🇱',
                    "ğŸ‡¯ğŸ‡µ": 'Japan 🇯🇵',
                    "ğŸ‡¨ğŸ‡³": 'China 🇨🇳',
                    "ğŸ‡¨ğŸ‡¦": 'Canada 🇨🇦',
                    "ğŸ��": 'Referee'
                    }

good_flags_2 = {"ğŸ‡©ğŸ‡ª":'🇩🇪',
                    "ğŸ‡ºğŸ‡¸":'🇺🇲',
                    "ğŸ‡°ğŸ‡·":'🇰🇷',
                    "ğŸ‡¬ğŸ‡§":'🇬🇧',
                    "ğŸ‡¨ğŸ‡µ":'🇫🇷',
                    "oviet":'☭',
                    "ğŸ‡¦ğŸ‡º":'🇦🇺',
                    "ğŸ‡­ğŸ‡º":'🇭🇺',
                    "ğŸ‡³ğŸ‡¿":'🇳🇿',
                    "ğŸ‡®ğŸ‡¹":'🇮🇹',
                    "ğŸ‡¦ğŸ‡·":'🇦🇷',
                    "ğŸ‡³ğŸ‡±":'🇳🇱',
                    "ğŸ‡¯ğŸ‡µ":'🇯🇵',
                    "ğŸ‡¨ğŸ‡³":'🇨🇳',
                    "ğŸ‡¨ğŸ‡¦":'🇨🇦',
                    "ğŸ��": 'Referee'
                    }


good_team_names_with_flag =['Germany 🇩🇪', 'United States 🇺🇲', 'South Korea 🇰🇷', 'Great Britain 🇬🇧', 
'France 🇫🇷','The Soviet Union ☭', 'Australia 🇦🇺', 'Hungary 🇭🇺', 'New Zealand 🇳🇿', 
    'Italy 🇮🇹','Argentina 🇦🇷', 'Netherlands 🇳🇱', 'Japan 🇯🇵','China 🇨🇳','Canada 🇨🇦',]
good_team_names_without_flag =['Germany', 'United States', 'South Korea', 'Great Britain', 
'France','The Soviet Union', 'Australia', 'Hungary', 'New Zealand', 
    'Italy','Argentina', 'Netherlands', 'Japan','China','Canada','Referee 6']

element_type_mapper = {
        2: "Defender",
        3: "Midfielder",
        4: "Forward",
        1: "Goalkeeper",
    }


all_managers_full_up_to_gw_8 = {56490: {0: {'first_name': 'Peyman',
   'last_name': 'Jafari',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  1: {'first_name': 'Mehrab',
   'last_name': 'Jafari',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'France 🇫🇷'},
  2: {'first_name': 'Ali',
   'last_name': 'Bazzi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'New Zealand 🇳🇿'},
  3: {'first_name': 'M. saleh',
   'last_name': 'Gharaei',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Great Britain 🇬🇧'},
  4: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  5: {'first_name': 'Hassan',
   'last_name': 'Paşa',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  6: {'first_name': 'Ali',
   'last_name': 'Lalehpour',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  7: {'first_name': 'Parham',
   'last_name': 'Khadivi',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 2,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  8: {'first_name': 'Hossein',
   'last_name': 'Veisi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 1,
   'fifths': 1,
   'country': 'South Korea 🇰🇷'},
  9: {'first_name': 'Hossein',
   'last_name': 'Naeiimii',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  10: {'first_name': 'Mehrzad',
   'last_name': 'Nadi',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  11: {'first_name': 'Arash',
   'last_name': 'Askari',
   'golds': 0,
   'silvers': 1,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  12: {'first_name': 'Javid',
   'last_name': 'Zaman',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  13: {'first_name': 'Arman',
   'last_name': 'Solkabon',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'The Soviet Union ☭'},
  14: {'first_name': 'Mahdi',
   'last_name': 'Mohammad zade',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Argentina 🇦🇷'},
  15: {'first_name': 'Amir',
   'last_name': 'Zamani',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'United States 🇺🇲'}},
 56760: {0: {'first_name': 'Ali',
   'last_name': 'Eslamy',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 2,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  1: {'first_name': 'Sina',
   'last_name': 'Mojallal',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 1,
   'country': 'Hungary 🇭🇺'},
  2: {'first_name': 'Khodadad',
   'last_name': 'Soltani',
   'golds': 3,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  3: {'first_name': 'Ali',
   'last_name': 'Omoomi',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 3,
   'country': 'Great Britain 🇬🇧'},
  4: {'first_name': 'Mehdi',
   'last_name': 'Pk',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'New Zealand 🇳🇿'},
  5: {'first_name': 'Pouyan',
   'last_name': 'Mp',
   'golds': 0,
   'silvers': 1,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  6: {'first_name': 'M.reza',
   'last_name': 'Bakhtafarid',
   'golds': 1,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  7: {'first_name': 'Foad',
   'last_name': 'Hesamarefi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  8: {'first_name': 'Reza',
   'last_name': 'Moradi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  9: {'first_name': 'Mmd',
   'last_name': 'Zangeneh',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  10: {'first_name': 'Vahid',
   'last_name': 'Yousefi',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  11: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  12: {'first_name': 'Javad',
   'last_name': 'Tajabad',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  13: {'first_name': 'Alireza',
   'last_name': 'Aghajani',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  14: {'first_name': 'Soltan',
   'last_name': 'Jir',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Italy 🇮🇹'},
  15: {'first_name': 'Amir',
   'last_name': 'Hossein',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Argentina 🇦🇷'}},
 57026: {0: {'first_name': 'Mohammadhosein',
   'last_name': 'Mokhtari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  1: {'first_name': 'Mohammadhasan',
   'last_name': 'Refahati',
   'golds': 3,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  2: {'first_name': 'Erfan',
   'last_name': 'Jebeli',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Great Britain 🇬🇧'},
  3: {'first_name': 'Mehdi',
   'last_name': 'Afshar',
   'golds': 1,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 2,
   'country': 'United States 🇺🇲'},
  4: {'first_name': 'Mohsen',
   'last_name': 'Zamani',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Italy 🇮🇹'},
  5: {'first_name': 'Omid',
   'last_name': 'Ghorbani',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Hungary 🇭🇺'},
  6: {'first_name': 'Arsene',
   'last_name': 'Wenger',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  7: {'first_name': 'Abbas',
   'last_name': 'Zolfigol',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  8: {'first_name': '_me8__',
   'last_name': 'Gunner',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  9: {'first_name': 'Luka',
   'last_name': 'Donä‡iä‡',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 2,
   'fifths': 0,
   'country': 'New Zealand 🇳🇿'},
  10: {'first_name': 'Ehsan',
   'last_name': 'Sahizadeh',
   'golds': 2,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  11: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  12: {'first_name': 'Behnam',
   'last_name': 'Moradi',
   'golds': 0,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  13: {'first_name': 'Nima',
   'last_name': 'Dashti',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'South Korea 🇰🇷'},
  14: {'first_name': 'Awmir',
   'last_name': 'Rashidabadi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'The Soviet Union ☭'},
  15: {'first_name': 'Matin',
   'last_name': 'Ganjali',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'China 🇨🇳'}},
 58512: {0: {'first_name': 'Amirfarhang',
   'last_name': 'Behzad',
   'golds': 0,
   'silvers': 1,
   'bronzes': 2,
   'fourths': 1,
   'fifths': 0,
   'country': 'Great Britain 🇬🇧'},
  1: {'first_name': 'Kaveh',
   'last_name': 'Ebrahimi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  2: {'first_name': 'Ù…ù‡ø¯ûœ',
   'last_name': 'Ø¬ø¹ù�ø±ûœ',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'United States 🇺🇲'},
  3: {'first_name': 'Won',
   'last_name': 'Tdm',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  4: {'first_name': 'Sina',
   'last_name': 'Honarpisheh',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  5: {'first_name': 'Amirhosein',
   'last_name': 'Zeininasab',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  6: {'first_name': 'Amir',
   'last_name': 'Mahdi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  7: {'first_name': 'Hamidreza',
   'last_name': 'Aghajani',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Canada 🇨🇦'},
  8: {'first_name': 'Mohammad saleh',
   'last_name': 'Samizadeh',
   'golds': 0,
   'silvers': 2,
   'bronzes': 2,
   'fourths': 1,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  9: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  10: {'first_name': 'Sajad',
   'last_name': 'Afroozi',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  11: {'first_name': 'Hossein',
   'last_name': 'Rm',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 2,
   'country': 'Italy 🇮🇹'},
  12: {'first_name': 'Sina',
   'last_name': 'Safarzaee',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'New Zealand 🇳🇿'},
  13: {'first_name': 'Hamid',
   'last_name': 'Ghorbani',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Australia 🇦🇺'},
  14: {'first_name': 'Reza',
   'last_name': 'Bagheri',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Argentina 🇦🇷'},
  15: {'first_name': 'Poorya',
   'last_name': 'Ebrahimi',
   'golds': 1,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 1,
   'country': 'South Korea 🇰🇷'}},
 58924: {0: {'first_name': 'Ali',
   'last_name': 'Mirshekaran',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 2,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  1: {'first_name': 'Milad',
   'last_name': 'Benam',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  2: {'first_name': 'Nikan',
   'last_name': 'Rahmani',
   'golds': 2,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'The Soviet Union ☭'},
  3: {'first_name': 'Ali',
   'last_name': 'Mohammadi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  4: {'first_name': 'Artin',
   'last_name': 'Gh',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  5: {'first_name': 'Omid',
   'last_name': 'Mousavi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  6: {'first_name': 'Alireza',
   'last_name': 'Tavakkoli',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 2,
   'country': 'Japan 🇯🇵'},
  7: {'first_name': 'Pooyan',
   'last_name': 'Khabooshani',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 2,
   'country': 'Netherlands 🇳🇱'},
  8: {'first_name': 'Hossein',
   'last_name': 'Lessani',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Argentina 🇦🇷'},
  9: {'first_name': 'El',
   'last_name': 'Profesor',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  10: {'first_name': 'Mohammad',
   'last_name': 'Mahdi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  11: {'first_name': 'Soroush',
   'last_name': 'Shojaei',
   'golds': 0,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  12: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  13: {'first_name': 'Amirhossein',
   'last_name': 'Zolfaghari',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 2,
   'country': 'Great Britain 🇬🇧'},
  14: {'first_name': 'Babak',
   'last_name': 'Khorasani',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  15: {'first_name': 'Alireza',
   'last_name': 'Noori',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'}},
 59081: {0: {'first_name': 'Mehdi',
   'last_name': 'Kalookhi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 2,
   'country': 'New Zealand 🇳🇿'},
  1: {'first_name': 'Porya',
   'last_name': 'Andalibi',
   'golds': 2,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  2: {'first_name': 'Imey',
   'last_name': 'Miley',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 2,
   'country': 'China 🇨🇳'},
  3: {'first_name': 'Seyyed mohammadhossein',
   'last_name': 'Ghasemi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Great Britain 🇬🇧'},
  4: {'first_name': 'Majid',
   'last_name': 'Benam',
   'golds': 2,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Germany 🇩🇪'},
  5: {'first_name': 'Seyed mohammad',
   'last_name': 'Moosavi',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  6: {'first_name': 'Yosef',
   'last_name': 'Khoshnood',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Netherlands 🇳🇱'},
  7: {'first_name': 'Parsa',
   'last_name': 'Ghafouri',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  8: {'first_name': 'Erfan',
   'last_name': 'Paksirat',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  9: {'first_name': 'Alimohammad',
   'last_name': 'Babaghorbani',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  10: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  11: {'first_name': 'Hadi',
   'last_name': 'Mohammady',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  12: {'first_name': 'Muhammad',
   'last_name': 'Esteghamat',
   'golds': 0,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 0,
   'country': 'Argentina 🇦🇷'},
  13: {'first_name': 'Saeed',
   'last_name': 'Adelzade',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 1,
   'country': 'France 🇫🇷'},
  14: {'first_name': 'Nima',
   'last_name': 'Hajimusaei',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  15: {'first_name': 'Ali',
   'last_name': 'Taheri',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'}},
 59176: {0: {'first_name': 'Mirsalari',
   'last_name': '27',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  1: {'first_name': 'Mahyar',
   'last_name': 'Rostami',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Italy 🇮🇹'},
  2: {'first_name': 'Surena',
   'last_name': 'Km',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 3,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  3: {'first_name': 'Omidreza',
   'last_name': 'Heydari',
   'golds': 2,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Great Britain 🇬🇧'},
  4: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 2,
   'fifths': 1,
   'country': 'Canada 🇨🇦'},
  5: {'first_name': 'Amir',
   'last_name': 'Tricko',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'France 🇫🇷'},
  6: {'first_name': 'Navid',
   'last_name': 'Foroughi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  7: {'first_name': 'Ali',
   'last_name': 'Hafizi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 2,
   'country': 'Japan 🇯🇵'},
  8: {'first_name': 'Abolfazl',
   'last_name': 'Keshavarz',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  9: {'first_name': 'Abbas',
   'last_name': 'Kalekhar',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'New Zealand 🇳🇿'},
  10: {'first_name': 'Abolfazl',
   'last_name': 'Rezapoor',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'China 🇨🇳'},
  11: {'first_name': 'Hasan',
   'last_name': 'Karimi',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  12: {'first_name': 'Amir',
   'last_name': 'Fathali',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Argentina 🇦🇷'},
  13: {'first_name': 'Ali mohamad',
   'last_name': 'Rahmani shamsi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  14: {'first_name': 'Parham',
   'last_name': 'Esmaelifard',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  15: {'first_name': 'Parham',
   'last_name': 'Esmaelifard',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Australia 🇦🇺'}},
 59219: {0: {'first_name': 'Tooraj',
   'last_name': 'Karami',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  1: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  2: {'first_name': 'Amirmahdi',
   'last_name': 'Asadi',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Australia 🇦🇺'},
  3: {'first_name': 'Pouria',
   'last_name': 'Tahmasbi',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  4: {'first_name': 'Mehrab',
   'last_name': 'King',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Hungary 🇭🇺'},
  5: {'first_name': 'Farshad',
   'last_name': 'Yazdani',
   'golds': 1,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  6: {'first_name': 'Parsa',
   'last_name': 'Noroozi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 2,
   'fifths': 0,
   'country': 'New Zealand 🇳🇿'},
  7: {'first_name': 'Alireza',
   'last_name': 'Ramezani',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Netherlands 🇳🇱'},
  8: {'first_name': 'Navid',
   'last_name': 'Mig',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  9: {'first_name': 'Parsa',
   'last_name': 'Maleknejad',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Great Britain 🇬🇧'},
  10: {'first_name': 'A',
   'last_name': 'B',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  11: {'first_name': 'Mh',
   'last_name': 'Sajadifar',
   'golds': 2,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  12: {'first_name': 'Behnam',
   'last_name': 'Astaraki',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'China 🇨🇳'},
  13: {'first_name': 'Sina',
   'last_name': 'Mirzaeei',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  14: {'first_name': 'Tractor',
   'last_name': 'Barcelona',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  15: {'first_name': 'Mohammad sadegh',
   'last_name': 'Mohammadpour',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0}},
 60061: {0: {'first_name': 'Ali',
   'last_name': 'Khosravi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'New Zealand 🇳🇿'},
  1: {'first_name': 'Emad',
   'last_name': 'Alikhani',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 2,
   'country': 'United States 🇺🇲'},
  2: {'first_name': 'Ali',
   'last_name': 'Rezaee',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  3: {'first_name': 'Akbar',
   'last_name': 'Sarabi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'China 🇨🇳'},
  4: {'first_name': 'Mohammadhossein',
   'last_name': 'Masoumi',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  5: {'first_name': 'Sina',
   'last_name': 'Zeinali',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 2,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  6: {'first_name': 'Hamed',
   'last_name': 'Dinarvand',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Australia 🇦🇺'},
  7: {'first_name': 'Rasool',
   'last_name': 'Gunners',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  8: {'first_name': 'Ilia',
   'last_name': 'Mahdilou',
   'golds': 2,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  9: {'first_name': 'Feriburz',
   'last_name': 'Muradi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Netherlands 🇳🇱'},
  10: {'first_name': 'Arshia',
   'last_name': 'Mohammadi',
   'golds': 0,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  11: {'first_name': 'Sed',
   'last_name': 'Rashid',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  12: {'first_name': 'Amirabbas',
   'last_name': 'Nesaee',
   'golds': 0,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 1,
   'fifths': 0,
   'country': 'Great Britain 🇬🇧'},
  13: {'first_name': 'Amir hossein',
   'last_name': 'Esmaili',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'The Soviet Union ☭'},
  14: {'first_name': 'Rezaynwa',
   'last_name': 'Iran',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  15: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0}},
 60068: {0: {'first_name': 'Mahdi',
   'last_name': 'Sadavi',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  1: {'first_name': 'Mohamad sepehr',
   'last_name': 'Golshan',
   'golds': 1,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 1,
   'country': 'South Korea 🇰🇷'},
  2: {'first_name': 'Milad',
   'last_name': 'Zare',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  3: {'first_name': 'Mahdi',
   'last_name': 'Amanollah zade',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  4: {'first_name': 'Amir',
   'last_name': 'Hossein',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 2,
   'country': 'Canada 🇨🇦'},
  5: {'first_name': 'Mohammad',
   'last_name': 'Mohammadi shoure',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  6: {'first_name': 'É¦ö…ö…ê�çÿõ¼',
   'last_name': 'Õ¼ê‹é›',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  7: {'first_name': 'Mehdi',
   'last_name': 'Abbastabaar',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Great Britain 🇬🇧'},
  8: {'first_name': 'M.mehdi',
   'last_name': '.kor',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  9: {'first_name': 'Nima',
   'last_name': 'Mokarram',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 1,
   'country': 'Australia 🇦🇺'},
  10: {'first_name': 'Taji',
   'last_name': '7',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Japan 🇯🇵'},
  11: {'first_name': 'M.m',
   'last_name': 'Sh',
   'golds': 0,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  12: {'first_name': 'Mohammad',
   'last_name': 'Pakdelian',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  13: {'first_name': 'Roozbeh',
   'last_name': 'Mollahaji',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  14: {'first_name': 'Mahyar',
   'last_name': 'Talari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  15: {'first_name': 'Mohammad sadegh',
   'last_name': 'Sahraei',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'United States 🇺🇲'}},
 60279: {0: {'first_name': 'Adel',
   'last_name': 'Hagh mohammady',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  1: {'first_name': 'Farzad',
   'last_name': 'Saeidi',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  2: {'first_name': 'Mohamadreza',
   'last_name': 'Choopani',
   'golds': 2,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Germany 🇩🇪'},
  3: {'first_name': 'Mohammad',
   'last_name': 'Fallahi',
   'golds': 2,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Hungary 🇭🇺'},
  4: {'first_name': 'Amirhosein',
   'last_name': 'Shirafkan',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'The Soviet Union ☭'},
  5: {'first_name': 'Smd',
   'last_name': 'Mehdi',
   'golds': 0,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Netherlands 🇳🇱'},
  6: {'first_name': 'Amir',
   'last_name': 'Rtp',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 2,
   'country': 'France 🇫🇷'},
  7: {'first_name': 'Maryam',
   'last_name': 'Hadizadeh',
   'golds': 0,
   'silvers': 2,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Great Britain 🇬🇧'},
  8: {'first_name': 'Amirhossein',
   'last_name': 'Barzin',
   'golds': 1,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'Italy 🇮🇹'},
  9: {'first_name': 'S.taha.',
   'last_name': 'H.j',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Canada 🇨🇦'},
  10: {'first_name': 'Hala',
   'last_name': 'Madrid',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  11: {'first_name': 'Darwin',
   'last_name': '27',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  12: {'first_name': 'Navid',
   'last_name': 'Mahmoodi nezhad',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'United States 🇺🇲'},
  13: {'first_name': 'Nima',
   'last_name': 'Hajimusaei',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  14: {'first_name': 'Hossein',
   'last_name': 'Kashi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'Japan 🇯🇵'},
  15: {'first_name': 'Arshia',
   'last_name': 'Mo',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'New Zealand 🇳🇿'}},
 60283: {0: {'first_name': 'Benyamin',
   'last_name': 'Mohammadi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 1,
   'country': 'The Soviet Union ☭'},
  1: {'first_name': 'Hossein',
   'last_name': 'Bahremand',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Argentina 🇦🇷'},
  2: {'first_name': 'Samad',
   'last_name': 'Barati',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 1,
   'fifths': 0,
   'country': 'New Zealand 🇳🇿'},
  3: {'first_name': 'Amirhosein',
   'last_name': 'Jalali',
   'golds': 1,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Netherlands 🇳🇱'},
  4: {'first_name': 'Hassan',
   'last_name': 'Ghorbani',
   'golds': 0,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Canada 🇨🇦'},
  5: {'first_name': 'Nima',
   'last_name': 'Qasemi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'China 🇨🇳'},
  6: {'first_name': 'Mohamad',
   'last_name': 'Yousefi',
   'golds': 2,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0,
   'country': 'South Korea 🇰🇷'},
  7: {'first_name': 'Farzan',
   'last_name': 'Esrafili',
   'golds': 0,
   'silvers': 0,
   'bronzes': 2,
   'fourths': 0,
   'fifths': 2,
   'country': 'United States 🇺🇲'},
  8: {'first_name': 'Ali',
   'last_name': 'Jalilvand',
   'golds': 1,
   'silvers': 2,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'France 🇫🇷'},
  9: {'first_name': 'Reza',
   'last_name': 'Sadeghi',
   'golds': 0,
   'silvers': 0,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 1,
   'country': 'Italy 🇮🇹'},
  10: {'first_name': 'Alireza',
   'last_name': 'Maleki',
   'golds': 2,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Australia 🇦🇺'},
  11: {'first_name': 'Majid',
   'last_name': 'Jafari',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 1,
   'country': 'Japan 🇯🇵'},
  12: {'first_name': 'Nima',
   'last_name': 'Hajimusaei',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 0,
   'fifths': 0},
  13: {'first_name': 'Mahdi',
   'last_name': 'Ghanbarian',
   'golds': 1,
   'silvers': 1,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 0,
   'country': 'Hungary 🇭🇺'},
  14: {'first_name': 'Amin',
   'last_name': 'Delshad',
   'golds': 0,
   'silvers': 1,
   'bronzes': 1,
   'fourths': 0,
   'fifths': 0,
   'country': 'Germany 🇩🇪'},
  15: {'first_name': 'Seyed alireza',
   'last_name': 'Hosseini',
   'golds': 0,
   'silvers': 0,
   'bronzes': 0,
   'fourths': 1,
   'fifths': 1,
   'country': 'Great Britain 🇬🇧'}}}

managers_league_dic_2 = {56490: {0: {'country': 'China 🇨🇳',
             'first_name': 'Peyman',
             'last_name': 'Jafari'},
         1: {'country': 'France 🇫🇷',
             'first_name': 'Mehrab',
             'last_name': 'Jafari'},
         2: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Ali',
             'last_name': 'Bazzi'},
         3: {'country': 'Great Britain 🇬🇧',
             'first_name': 'M. saleh',
             'last_name': 'Gharaei'},
         4: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         5: {'country': 'Japan 🇯🇵',
             'first_name': 'Hassan',
             'last_name': 'Paåÿa'},
         6: {'country': 'Canada 🇨🇦',
             'first_name': 'Ali',
             'last_name': 'Lalehpour'},
         7: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Parham',
             'last_name': 'Khadivi'},
         8: {'country': 'South Korea 🇰🇷',
             'first_name': 'Hossein',
             'last_name': 'Veisi'},
         9: {'country': 'Australia 🇦🇺',
             'first_name': 'Hossein',
             'last_name': 'Naeiimii'},
         10: {'country': 'Italy 🇮🇹',
              'first_name': 'Mehrzad',
              'last_name': 'Nadi'},
         11: {'country': 'Germany 🇩🇪',
              'first_name': 'Arash',
              'last_name': 'Askari'},
         12: {'country': 'Hungary 🇭🇺',
              'first_name': 'Javid',
              'last_name': 'Zaman'},
         13: {'country': 'The Soviet Union ☭',
              'first_name': 'Arman',
              'last_name': 'Solkabon'},
         14: {'country': 'Argentina 🇦🇷',
              'first_name': 'Mahdi',
              'last_name': 'Mohammad zade'},
         15: {'country': 'United States 🇺🇲',
              'first_name': 'Amir',
              'last_name': 'Zamani'}},
 56760: {0: {'country': 'South Korea 🇰🇷',
             'first_name': 'Ali',
             'last_name': 'Eslamy'},
         1: {'country': 'Hungary 🇭🇺',
             'first_name': 'Sina',
             'last_name': 'Mojallal'},
         2: {'country': 'Germany 🇩🇪',
             'first_name': 'Khodadad',
             'last_name': 'Soltani'},
         3: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Ali',
             'last_name': 'Omoomi'},
         4: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Mehdi',
             'last_name': 'Pk'},
         5: {'country': 'Canada 🇨🇦', 'first_name': 'Pouyan', 'last_name': 'Mp'},
         6: {'country': 'The Soviet Union ☭',
             'first_name': 'M.reza',
             'last_name': 'Bakhtafarid'},
         7: {'country': 'Australia 🇦🇺',
             'first_name': 'Foad',
             'last_name': 'Hesamarefi'},
         8: {'country': 'Japan 🇯🇵',
             'first_name': 'Reza',
             'last_name': 'Moradi'},
         9: {'country': 'China 🇨🇳',
             'first_name': 'Mmd',
             'last_name': 'Zangeneh'},
         10: {'country': 'United States 🇺🇲',
              'first_name': 'Vahid',
              'last_name': 'Yousefi'},
         11: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         12: {'country': 'France 🇫🇷',
              'first_name': 'Javad',
              'last_name': 'Tajabad'},
         13: {'country': 'Netherlands 🇳🇱',
              'first_name': 'Alireza',
              'last_name': 'Aghajani'},
         14: {'country': 'Italy 🇮🇹',
              'first_name': 'Soltan',
              'last_name': 'Jir'},
         15: {'country': 'Argentina 🇦🇷',
              'first_name': 'Amir',
              'last_name': 'Hossein'}},
 57026: {0: {'first_name': 'Mohammadhosein', 'last_name': 'Mokhtari',
 'country': 'Argentina 🇦🇷'},
         1: {'country': 'Canada 🇨🇦',
             'first_name': 'Mohammadhasan',
             'last_name': 'Refahati'},
         2: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Erfan',
             'last_name': 'Jebeli'},
         3: {'country': 'United States 🇺🇲',
             'first_name': 'Mehdi',
             'last_name': 'Afshar'},
         4: {'country': 'Italy 🇮🇹',
             'first_name': 'Mohsen',
             'last_name': 'Zamani'},
         5: {'country': 'Hungary 🇭🇺',
             'first_name': 'Omid',
             'last_name': 'Ghorbani'},
         6: {'first_name': 'Arsene', 'last_name': 'Wenger', 'country': 'Netherlands 🇳🇱',},
         7: {'country': 'Australia 🇦🇺',
             'first_name': 'Abbas',
             'last_name': 'Zolfigol'},
         8: {'country': 'Japan 🇯🇵',
             'first_name': '_me8__',
             'last_name': 'Gunner'},
         9: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Luka',
             'last_name': 'Donä‡iä‡'},
         10: {'country': 'Germany 🇩🇪',
              'first_name': 'Ehsan',
              'last_name': 'Sahizadeh'},
         11: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         12: {'country': 'France 🇫🇷',
              'first_name': 'Behnam',
              'last_name': 'Moradi'},
         13: {'country': 'South Korea 🇰🇷',
              'first_name': 'Nima',
              'last_name': 'Dashti'},
         14: {'country': 'The Soviet Union ☭',
              'first_name': 'Awmir',
              'last_name': 'Rashidabadi'},
         15: {'country': 'China 🇨🇳',
              'first_name': 'Matin',
              'last_name': 'Ganjali'}},
 58512: {0: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Amirfarhang',
             'last_name': 'Behzad'},
         1: {'country': 'Germany 🇩🇪',
             'first_name': 'Kaveh',
             'last_name': 'Ebrahimi'},
         2: {'country': 'United States 🇺🇲',
             'first_name': 'Mahdi',
             'last_name': 'Jafari'},
         3: {'country': 'The Soviet Union ☭',
             'first_name': 'Won',
             'last_name': 'Tdm'},
         4: {'country': 'China 🇨🇳',
             'first_name': 'Sina',
             'last_name': 'Honarpisheh'},
         5: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Amirhosein',
             'last_name': 'Zeininasab'},
         6: {'country': 'France 🇫🇷',
             'first_name': 'Amir',
             'last_name': 'Mahdi'},
         7: {'country': 'Canada 🇨🇦',
             'first_name': 'Hamidreza',
             'last_name': 'Aghajani'},
         8: {'country': 'Hungary 🇭🇺',
             'first_name': 'Mohammad saleh',
             'last_name': 'Samizadeh'},
         9: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         10: {'country': 'Japan 🇯🇵',
              'first_name': 'Sajad',
              'last_name': 'Afroozi'},
         11: {'country': 'Italy 🇮🇹',
              'first_name': 'Hossein',
              'last_name': 'Rm'},
         12: {'country': 'New Zealand 🇳🇿',
              'first_name': 'Sina',
              'last_name': 'Safarzaee'},
         13: {'country': 'Australia 🇦🇺',
              'first_name': 'Hamid',
              'last_name': 'Ghorbani'},
         14: {'country': 'Argentina 🇦🇷',
              'first_name': 'Reza',
              'last_name': 'Bagheri'},
         15: {'country': 'South Korea 🇰🇷',
              'first_name': 'Poorya',
              'last_name': 'Ebrahimi'}},
 58924: {0: {'country': 'South Korea 🇰🇷',
             'first_name': 'Ali',
             'last_name': 'Mirshekaran'},
         1: {'country': 'Germany 🇩🇪',
             'first_name': 'Milad',
             'last_name': 'Benam'},
         2: {'country': 'The Soviet Union ☭',
             'first_name': 'Nikan',
             'last_name': 'Rahmani'},
         3: {'country': 'Italy 🇮🇹',
             'first_name': 'Ali',
             'last_name': 'Mohammadi'},
         4: {'first_name': 'Artin', 'last_name': 'Gh', 'country': 'China 🇨🇳'},
         5: {'country': 'Australia 🇦🇺',
             'first_name': 'Omid',
             'last_name': 'Mousavi'},
         6: {'country': 'Japan 🇯🇵',
             'first_name': 'Alireza',
             'last_name': 'Tavakkoli'},
         7: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Pooyan',
             'last_name': 'Khabooshani'},
         8: {'country': 'Argentina 🇦🇷',
             'first_name': 'Hossein',
             'last_name': 'Lessani'},
         9: {'first_name': 'El', 'last_name': 'Profesor', 'country': 'New Zealand 🇳🇿'},
         10: {'country': 'United States 🇺🇲',
              'first_name': 'Mohammad',
              'last_name': 'Mahdi'},
         11: {'country': 'France 🇫🇷',
              'first_name': 'Soroush',
              'last_name': 'Shojaei'},
         12: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         13: {'country': 'Great Britain 🇬🇧',
              'first_name': 'Amirhossein',
              'last_name': 'Zolfaghari'},
         14: {'country': 'Canada 🇨🇦',
              'first_name': 'Babak',
              'last_name': 'Khorasani'},
         15: {'country': 'Hungary 🇭🇺',
              'first_name': 'Alireza',
              'last_name': 'Noori'}},
 59081: {0: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Mehdi',
             'last_name': 'Kalookhi'},
         1: {'country': 'South Korea 🇰🇷',
             'first_name': 'Porya',
             'last_name': 'Andalibi'},
         2: {'country': 'China 🇨🇳', 'first_name': 'Imey', 'last_name': 'Miley'},
         3: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Seyyed mohammadhossein',
             'last_name': 'Ghasemi'},
         4: {'country': 'Germany 🇩🇪',
             'first_name': 'Majid',
             'last_name': 'Benam'},
         5: {'country': 'Japan 🇯🇵',
             'first_name': 'Seyed mohammad',
             'last_name': 'Moosavi'},
         6: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Yosef',
             'last_name': 'Khoshnood'},
         7: {'country': 'United States 🇺🇲',
             'first_name': 'Parsa',
             'last_name': 'Ghafouri'},
         8: {'country': 'Italy 🇮🇹',
             'first_name': 'Erfan',
             'last_name': 'Paksirat'},
         9: {'country': 'Australia 🇦🇺',
             'first_name': 'Alimohammad',
             'last_name': 'Babaghorbani'},
         10: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         11: {'country': 'The Soviet Union ☭',
              'first_name': 'Hadi',
              'last_name': 'Mohammady'},
         12: {'country': 'Argentina 🇦🇷',
              'first_name': 'Muhammad',
              'last_name': 'Esteghamat'},
         13: {'country': 'France 🇫🇷',
              'first_name': 'Saeed',
              'last_name': 'Adelzade'},
         14: {'country': 'Canada 🇨🇦',
              'first_name': 'Nima',
              'last_name': 'Hajimusaei'},
         15: {'country': 'Hungary 🇭🇺',
              'first_name': 'Ali',
              'last_name': 'Taheri'}},
 59176: {0: {'country': 'The Soviet Union ☭',
             'first_name': 'Mirsalari',
             'last_name': '27'},
         1: {'country': 'Italy 🇮🇹',
             'first_name': 'Mahyar',
             'last_name': 'Rostami'},
         2: {'country': 'South Korea 🇰🇷',
             'first_name': 'Surena',
             'last_name': 'Km'},
         3: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Omidreza',
             'last_name': 'Heydari'},
         4: {'country': 'Canada 🇨🇦',
             'first_name': 'Mahyar',
             'last_name': 'Talari'},
         5: {'country': 'France 🇫🇷',
             'first_name': 'Amir',
             'last_name': 'Tricko'},
         6: {'country': 'Germany 🇩🇪',
             'first_name': 'Navid',
             'last_name': 'Foroughi'},
         7: {'country': 'Japan 🇯🇵', 'first_name': 'Ali', 'last_name': 'Hafizi'},
         8: {'country': 'United States 🇺🇲',
             'first_name': 'Abolfazl',
             'last_name': 'Keshavarz'},
         9: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Abbas',
             'last_name': 'Kalekhar'},
         10: {'country': 'China 🇨🇳',
              'first_name': 'Abolfazl',
              'last_name': 'Rezapoor'},
         11: {'country': 'Netherlands 🇳🇱',
              'first_name': 'Hasan',
              'last_name': 'Karimi'},
         12: {'country': 'Argentina 🇦🇷',
              'first_name': 'Amir',
              'last_name': 'Fathali'},
         13: {'country': 'Hungary 🇭🇺',
              'first_name': 'Ali mohamad',
              'last_name': 'Rahmani shamsi'},
         14: {'country': 'Australia 🇦🇺',
              'first_name': 'Parham',
              'last_name': 'Esmaelifard'},
         15: {'country': 'Australia 🇦🇺',
              'first_name': 'Parham',
              'last_name': 'Esmaelifard'}},
 59219: {0: {'country': 'France 🇫🇷',
             'first_name': 'Tooraj',
             'last_name': 'Karami'},
         1: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         2: {'country': 'Australia 🇦🇺',
             'first_name': 'Amirmahdi',
             'last_name': 'Asadi'},
         3: {'country': 'United States 🇺🇲',
             'first_name': 'Pouria',
             'last_name': 'Tahmasbi'},
         4: {'country': 'Hungary 🇭🇺',
             'first_name': 'Mehrab',
             'last_name': 'King'},
         5: {'country': 'Italy 🇮🇹',
             'first_name': 'Farshad',
             'last_name': 'Yazdani'},
         6: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Parsa',
             'last_name': 'Noroozi'},
         7: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Alireza',
             'last_name': 'Ramezani'},
         8: {'country': 'Canada 🇨🇦', 'first_name': 'Navid', 'last_name': 'Mig'},
         9: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Parsa',
             'last_name': 'Maleknejad'},
         10: {'country': 'South Korea 🇰🇷', 'first_name': 'A', 'last_name': 'B'},
         11: {'country': 'The Soviet Union ☭',
              'first_name': 'Mh',
              'last_name': 'Sajadifar'},
         12: {'country': 'China 🇨🇳',
              'first_name': 'Behnam',
              'last_name': 'Astaraki'},
         13: {'country': 'Germany 🇩🇪',
              'first_name': 'Sina',
              'last_name': 'Mirzaeei'},
         14: {'first_name': 'Tractor', 'last_name': 'Barcelona', 'country': 'Japan 🇯🇵'},
         15: {'first_name': 'Mohammad sadegh', 'last_name': 'Mohammadpour', 'country': 'Argentina 🇦🇷'}},
 60061: {0: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Ali',
             'last_name': 'Khosravi'},
         1: {'country': 'United States 🇺🇲',
             'first_name': 'Emad',
             'last_name': 'Alikhani'},
         2: {'country': 'France 🇫🇷',
             'first_name': 'Ali',
             'last_name': 'Rezaee'},
         3: {'country': 'China 🇨🇳',
             'first_name': 'Akbar',
             'last_name': 'Sarabi'},
         4: {'country': 'Canada 🇨🇦',
             'first_name': 'Mohammadhossein',
             'last_name': 'Masoumi'},
         5: {'country': 'South Korea 🇰🇷',
             'first_name': 'Sina',
             'last_name': 'Zeinali'},
         6: {'country': 'Australia 🇦🇺',
             'first_name': 'Hamed',
             'last_name': 'Dinarvand'},
         7: {'country': 'Japan 🇯🇵',
             'first_name': 'Rasool',
             'last_name': 'Gunners'},
         8: {'country': 'Hungary 🇭🇺',
             'first_name': 'Ilia',
             'last_name': 'Mahdilou'},
         9: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Feriburz',
             'last_name': 'Muradi'},
         10: {'country': 'Italy 🇮🇹',
              'first_name': 'Arshia',
              'last_name': 'Mohammadi'},
         11: {'country': 'Germany 🇩🇪',
              'first_name': 'Sed',
              'last_name': 'Rashid'},
         12: {'country': 'Great Britain 🇬🇧',
              'first_name': 'Amirabbas',
              'last_name': 'Nesaee'},
         13: {'country': 'The Soviet Union ☭',
              'first_name': 'Amir hossein',
              'last_name': 'Esmaili'},
         14: {'first_name': 'Rezaynwa', 'last_name': 'Iran', 'country': 'Argentina 🇦🇷'},
         15: {'first_name': 'Mahyar', 'last_name': 'Talari'}},
 60068: {0: {'country': 'Hungary 🇭🇺',
             'first_name': 'Mahdi',
             'last_name': 'Sadavi'},
         1: {'country': 'South Korea 🇰🇷',
             'first_name': 'Mohamad sepehr',
             'last_name': 'Golshan'},
         2: {'country': 'Italy 🇮🇹', 'first_name': 'Milad', 'last_name': 'Zare'},
         3: {'first_name': 'Mahdi', 'last_name': 'Amanollah zade', 'country': 'Argentina 🇦🇷'},
         4: {'country': 'Canada 🇨🇦',
             'first_name': 'Amir',
             'last_name': 'Hossein'},
         5: {'country': 'The Soviet Union ☭',
             'first_name': 'Mohammad',
             'last_name': 'Mohammadi shoure'},
         6: {'country': 'France 🇫🇷',
             'first_name': 'ɦօօʍǟռ',
             'last_name': 'ռʋɛ'},
         7: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Mehdi',
             'last_name': 'Abbastabaar'},
         8: {'country': 'Netherlands 🇳🇱',
             'first_name': 'M.mehdi',
             'last_name': '.kor'},
         9: {'country': 'Australia 🇦🇺',
             'first_name': 'Nima',
             'last_name': 'Mokarram'},
         10: {'country': 'Japan 🇯🇵', 'first_name': 'Taji', 'last_name': '7'},
         11: {'country': 'China 🇨🇳', 'first_name': 'M.m', 'last_name': 'Sh'},
         12: {'country': 'Germany 🇩🇪',
              'first_name': 'Mohammad',
              'last_name': 'Pakdelian'},
         13: {'first_name': 'Roozbeh', 'last_name': 'Mollahaji', 'country': 'New Zealand 🇳🇿'},
         14: {'first_name': 'Mahyar', 'last_name': 'Talari'},
         15: {'country': 'United States 🇺🇲',
              'first_name': 'Mohammad sadegh',
              'last_name': 'Sahraei'}},
 60279: {0: {'first_name': 'Adel', 'last_name': 'Hagh mohammady', 'country': 'Argentina 🇦🇷'},
         1: {'country': 'South Korea 🇰🇷',
             'first_name': 'Farzad',
             'last_name': 'Saeidi'},
         2: {'country': 'Germany 🇩🇪',
             'first_name': 'Mohamadreza',
             'last_name': 'Choopani'},
         3: {'country': 'Hungary 🇭🇺',
             'first_name': 'Mohammad',
             'last_name': 'Fallahi'},
         4: {'country': 'The Soviet Union ☭',
             'first_name': 'Amirhosein',
             'last_name': 'Shirafkan'},
         5: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Smd',
             'last_name': 'Mehdi'},
         6: {'country': 'France 🇫🇷', 'first_name': 'Amir', 'last_name': 'Rtp'},
         7: {'country': 'Great Britain 🇬🇧',
             'first_name': 'Maryam',
             'last_name': 'Hadizadeh'},
         8: {'country': 'Italy 🇮🇹',
             'first_name': 'Amirhossein',
             'last_name': 'Barzin'},
         9: {'country': 'Canada 🇨🇦',
             'first_name': 'S.taha.',
             'last_name': 'H.j'},
         10: {'country': 'China 🇨🇳',
              'first_name': 'Hala',
              'last_name': 'Madrid'},
         11: {'country': 'Australia 🇦🇺',
              'first_name': 'Darwin',
              'last_name': '27'},
         12: {'country': 'United States 🇺🇲',
              'first_name': 'Navid',
              'last_name': 'Mahmoodi nezhad'},
         13: {'first_name': 'Nima', 'last_name': 'Hajimusaei'},
         14: {'country': 'Japan 🇯🇵',
              'first_name': 'Hossein',
              'last_name': 'Kashi'},
         15: {'country': 'New Zealand 🇳🇿',
              'first_name': 'Arshia',
              'last_name': 'Mo'}},
 60283: {0: {'country': 'The Soviet Union ☭',
             'first_name': 'Benyamin',
             'last_name': 'Mohammadi'},
         1: {'country': 'Argentina 🇦🇷',
             'first_name': 'Hossein',
             'last_name': 'Bahremand'},
         2: {'country': 'New Zealand 🇳🇿',
             'first_name': 'Samad',
             'last_name': 'Barati'},
         3: {'country': 'Netherlands 🇳🇱',
             'first_name': 'Amirhosein',
             'last_name': 'Jalali'},
         4: {'country': 'Canada 🇨🇦',
             'first_name': 'Hassan',
             'last_name': 'Ghorbani'},
         5: {'country': 'China 🇨🇳',
             'first_name': 'Nima',
             'last_name': 'Qasemi'},
         6: {'country': 'South Korea 🇰🇷',
             'first_name': 'Mohamad',
             'last_name': 'Yousefi'},
         7: {'country': 'United States 🇺🇲',
             'first_name': 'Farzan',
             'last_name': 'Esrafili'},
         8: {'country': 'France 🇫🇷',
             'first_name': 'Ali',
             'last_name': 'Jalilvand'},
         9: {'country': 'Italy 🇮🇹',
             'first_name': 'Reza',
             'last_name': 'Sadeghi'},
         10: {'country': 'Australia 🇦🇺',
              'first_name': 'Alireza',
              'last_name': 'Maleki'},
         11: {'country': 'Japan 🇯🇵',
              'first_name': 'Majid',
              'last_name': 'Jafari'},
         12: {'first_name': 'Nima', 'last_name': 'Hajimusaei'},
         13: {'country': 'Hungary 🇭🇺',
              'first_name': 'Mahdi',
              'last_name': 'Ghanbarian'},
         14: {'country': 'Germany 🇩🇪',
              'first_name': 'Amin',
              'last_name': 'Delshad'},
         15: {'country': 'Great Britain 🇬🇧',
              'first_name': 'Seyed alireza',
              'last_name': 'Hosseini'}}}

# This is an empty dic which will be updated based on the m,edals each week.
# Key:  ('Germany 🇩🇪', 56760)
# Value:  ['Khodadad Soltani', [0, 0, 0, 0, 0]],
mappers_dic = {('China 🇨🇳', 56490): ['Peyman Jafari', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 56490): ['Mehrab Jafari', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 56490): ['Ali Bazzi', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 56490): ['M. saleh Gharaei', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 56490): ['Hassan Paåÿa', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 56490): ['Ali Lalehpour', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 56490): ['Parham Khadivi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 56490): ['Hossein Veisi', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 56490): ['Hossein Naeiimii', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 56490): ['Mehrzad Nadi', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 56490): ['Arash Askari', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 56490): ['Javid Zaman', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 56490): ['Arman Solkabon', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 56490): ['Mahdi Mohammad zade', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 56490): ['Amir Zamani', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 56760): ['Ali Eslamy', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 56760): ['Sina Mojallal', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 56760): ['Khodadad Soltani', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 56760): ['Ali Omoomi', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 56760): ['Mehdi Pk', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 56760): ['Pouyan Mp', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 56760): ['M.reza Bakhtafarid', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 56760): ['Foad Hesamarefi', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 56760): ['Reza Moradi', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 56760): ['Mmd Zangeneh', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 56760): ['Vahid Yousefi', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 56760): ['Javad Tajabad', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 56760): ['Alireza Aghajani', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 56760): ['Soltan Jir', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 56760): ['Amir Hossein', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 57026): ['Mohammadhosein Mokhtari', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 57026): ['Mohammadhasan Refahati', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 57026): ['Erfan Jebeli', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 57026): ['Mehdi Afshar', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 57026): ['Mohsen Zamani', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 57026): ['Omid Ghorbani', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 57026): ['Arsene Wenger', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 57026): ['Abbas Zolfigol', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 57026): ['_me8__ Gunner', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 57026): ['Luka Donä‡iä‡', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 57026): ['Ehsan Sahizadeh', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 57026): ['Behnam Moradi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 57026): ['Nima Dashti', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 57026): ['Awmir Rashidabadi', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 57026): ['Matin Ganjali', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 58512): ['Amirfarhang Behzad', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 58512): ['Kaveh Ebrahimi', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 58512): ['Mahdi Jafari', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 58512): ['Won Tdm', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 58512): ['Sina Honarpisheh', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 58512): ['Amirhosein Zeininasab', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 58512): ['Amir Mahdi', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 58512): ['Hamidreza Aghajani', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 58512): ['Mohammad saleh Samizadeh', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 58512): ['Sajad Afroozi', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 58512): ['Hossein Rm', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 58512): ['Sina Safarzaee', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 58512): ['Hamid Ghorbani', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 58512): ['Reza Bagheri', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 58512): ['Poorya Ebrahimi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 58924): ['Ali Mirshekaran', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 58924): ['Milad Benam', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 58924): ['Nikan Rahmani', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 58924): ['Ali Mohammadi', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 58924): ['Artin Gh', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 58924): ['Omid Mousavi', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 58924): ['Alireza Tavakkoli', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 58924): ['Pooyan Khabooshani', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 58924): ['Hossein Lessani', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 58924): ['El Profesor', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 58924): ['Mohammad Mahdi', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 58924): ['Soroush Shojaei', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 58924): ['Amirhossein Zolfaghari', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 58924): ['Babak Khorasani', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 58924): ['Alireza Noori', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 59081): ['Mehdi Kalookhi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 59081): ['Porya Andalibi', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 59081): ['Imey Miley', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 59081): ['Seyyed mohammadhossein Ghasemi',
  [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 59081): ['Majid Benam', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 59081): ['Seyed mohammad Moosavi', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 59081): ['Yosef Khoshnood', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 59081): ['Parsa Ghafouri', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 59081): ['Erfan Paksirat', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 59081): ['Alimohammad Babaghorbani', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 59081): ['Hadi Mohammady', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 59081): ['Muhammad Esteghamat', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 59081): ['Saeed Adelzade', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 59081): ['Nima Hajimusaei', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 59081): ['Ali Taheri', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 59176): ['Mirsalari 27', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 59176): ['Mahyar Rostami', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 59176): ['Surena Km', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 59176): ['Omidreza Heydari', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 59176): ['Mahyar Talari', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 59176): ['Amir Tricko', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 59176): ['Navid Foroughi', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 59176): ['Ali Hafizi', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 59176): ['Abolfazl Keshavarz', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 59176): ['Abbas Kalekhar', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 59176): ['Abolfazl Rezapoor', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 59176): ['Hasan Karimi', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 59176): ['Amir Fathali', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 59176): ['Ali mohamad Rahmani shamsi', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 59176): ['Parham Esmaelifard', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 59219): ['Tooraj Karami', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 59219): ['Amirmahdi Asadi', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 59219): ['Pouria Tahmasbi', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 59219): ['Mehrab King', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 59219): ['Farshad Yazdani', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 59219): ['Parsa Noroozi', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 59219): ['Alireza Ramezani', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 59219): ['Navid Mig', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 59219): ['Parsa Maleknejad', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 59219): ['A B', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 59219): ['Mh Sajadifar', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 59219): ['Behnam Astaraki', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 59219): ['Sina Mirzaeei', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 59219): ['Tractor Barcelona', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 59219): ['Mohammad sadegh Mohammadpour', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 60061): ['Ali Khosravi', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 60061): ['Emad Alikhani', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 60061): ['Ali Rezaee', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 60061): ['Akbar Sarabi', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 60061): ['Mohammadhossein Masoumi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 60061): ['Sina Zeinali', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 60061): ['Hamed Dinarvand', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 60061): ['Rasool Gunners', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 60061): ['Ilia Mahdilou', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 60061): ['Feriburz Muradi', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 60061): ['Arshia Mohammadi', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 60061): ['Sed Rashid', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 60061): ['Amirabbas Nesaee', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 60061): ['Amir hossein Esmaili', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 60061): ['Rezaynwa Iran', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 60068): ['Mahdi Sadavi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 60068): ['Mohamad sepehr Golshan', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 60068): ['Milad Zare', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 60068): ['Mahdi Amanollah zade', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 60068): ['Amir Hossein', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 60068): ['Mohammad Mohammadi shoure', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 60068): ['ɦօօʍǟռ ռʋɛ', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 60068): ['Mehdi Abbastabaar', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 60068): ['M.mehdi .kor', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 60068): ['Nima Mokarram', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 60068): ['Taji 7', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 60068): ['M.m Sh', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 60068): ['Mohammad Pakdelian', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 60068): ['Roozbeh Mollahaji', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 60068): ['Mohammad sadegh Sahraei', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 60279): ['Adel Hagh mohammady', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 60279): ['Farzad Saeidi', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 60279): ['Mohamadreza Choopani', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 60279): ['Mohammad Fallahi', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 60279): ['Amirhosein Shirafkan', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 60279): ['Smd Mehdi', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 60279): ['Amir Rtp', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 60279): ['Maryam Hadizadeh', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 60279): ['Amirhossein Barzin', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 60279): ['S.taha. H.j', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 60279): ['Hala Madrid', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 60279): ['Darwin 27', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 60279): ['Navid Mahmoodi nezhad', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 60279): ['Hossein Kashi', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 60279): ['Arshia Mo', [0, 0, 0, 0, 0]],
 ('The Soviet Union ☭', 60283): ['Benyamin Mohammadi', [0, 0, 0, 0, 0]],
 ('Argentina 🇦🇷', 60283): ['Hossein Bahremand', [0, 0, 0, 0, 0]],
 ('New Zealand 🇳🇿', 60283): ['Samad Barati', [0, 0, 0, 0, 0]],
 ('Netherlands 🇳🇱', 60283): ['Amirhosein Jalali', [0, 0, 0, 0, 0]],
 ('Canada 🇨🇦', 60283): ['Hassan Ghorbani', [0, 0, 0, 0, 0]],
 ('China 🇨🇳', 60283): ['Nima Qasemi', [0, 0, 0, 0, 0]],
 ('South Korea 🇰🇷', 60283): ['Mohamad Yousefi', [0, 0, 0, 0, 0]],
 ('United States 🇺🇲', 60283): ['Farzan Esrafili', [0, 0, 0, 0, 0]],
 ('France 🇫🇷', 60283): ['Ali Jalilvand', [0, 0, 0, 0, 0]],
 ('Italy 🇮🇹', 60283): ['Reza Sadeghi', [0, 0, 0, 0, 0]],
 ('Australia 🇦🇺', 60283): ['Alireza Maleki', [0, 0, 0, 0, 0]],
 ('Japan 🇯🇵', 60283): ['Majid Jafari', [0, 0, 0, 0, 0]],
 ('Hungary 🇭🇺', 60283): ['Mahdi Ghanbarian', [0, 0, 0, 0, 0]],
 ('Germany 🇩🇪', 60283): ['Amin Delshad', [0, 0, 0, 0, 0]],
 ('Great Britain 🇬🇧', 60283): ['Seyed alireza Hosseini', [0, 0, 0, 0, 0]]}